"""add image_column to book

Revision ID: 5da9e376478f
Revises: cd7cbd2e4b62
Create Date: 2024-10-15 09:47:00.714080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5da9e376478f'
down_revision = 'cd7cbd2e4b62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
